# Generated by Django 4.2.25 on 2025-11-05 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Flashcard',
        ),
        migrations.AlterField(
            model_name='card',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cards.category'),
        ),
    ]
